import assert from 'node:assert/strict'
import test from 'node:test'

import type { LabourMarketplaceSnapshot } from '../../lib/labour-marketplace'
import {
  COMPANY_MATCHING_DIGEST_CTA_URL,
  WHATSAPP_AUTOMATION_EVENT_RULES,
  buildWhatsappAutomationIdempotencyKey,
  getWhatsappAutomationCycleWindow,
  planCompanyMatchingDigests,
  planWorkerKycRejectedNotifications,
  planWorkerMatchingDigests,
  planWorkerPaymentOrPlanReminders,
} from '../../lib/whatsapp/automation-executor'

const makeSnapshot = (): LabourMarketplaceSnapshot => ({
  categories: [],
  plans: [],
  workers: [],
  companies: [],
  jobPosts: [],
  jobApplications: [],
  savedJobs: [],
  workerNotifications: [],
  walletTransactions: [],
  rechargeRequests: [],
  auditLogs: [],
  stats: {
    activeWorkers: 0,
    inactiveWorkers: 0,
    activeCompanies: 0,
    liveJobPosts: 0,
    totalWalletBalance: 0,
    recentAuditLogs: [],
  },
  storage: 'json',
})

test('automation rules allow only the approved four automatic WhatsApp event categories', () => {
  assert.deepEqual(Object.keys(WHATSAPP_AUTOMATION_EVENT_RULES).sort(), [
    'company_matching_digest',
    'worker_kyc_rejected',
    'worker_matching_digest',
    'worker_payment_or_plan_reminder',
  ])
  assert.equal(
    WHATSAPP_AUTOMATION_EVENT_RULES.company_matching_digest.recipientType,
    'company',
  )
  assert.equal(
    WHATSAPP_AUTOMATION_EVENT_RULES.worker_matching_digest.notificationPurpose,
    'matching',
  )
  assert.equal(
    WHATSAPP_AUTOMATION_EVENT_RULES.worker_payment_or_plan_reminder.notificationPurpose,
    'service',
  )
})

test('72-hour automation cycle windows are deterministic at exact boundaries', () => {
  assert.deepEqual(
    getWhatsappAutomationCycleWindow(new Date('2026-08-25T00:00:00.000Z')),
    {
      cycleStartsAt: '2026-08-23T00:00:00.000Z',
      cycleEndsAt: '2026-08-26T00:00:00.000Z',
    },
  )
  assert.deepEqual(
    getWhatsappAutomationCycleWindow(new Date('2026-08-26T23:59:59.999Z')),
    {
      cycleStartsAt: '2026-08-26T00:00:00.000Z',
      cycleEndsAt: '2026-08-29T00:00:00.000Z',
    },
  )
  assert.deepEqual(
    getWhatsappAutomationCycleWindow(new Date('2026-08-27T00:00:00.000Z')),
    {
      cycleStartsAt: '2026-08-26T00:00:00.000Z',
      cycleEndsAt: '2026-08-29T00:00:00.000Z',
    },
  )
})

test('company digest consolidates multiple live job posts into one masked dry-run plan', () => {
  const snapshot = makeSnapshot()
  snapshot.companies.push({
    id: 'company-1',
    companyName: 'ScaleVyapar Manufacturing',
    contactPerson: 'Owner',
    email: 'owner@example.com',
    mobile: '9876500000',
    contactMobile: '9876500000',
    businessType: 'Factory',
    industryCategory: 'Textile',
    gstNumber: '',
    companyAddress: '',
    state: 'Gujarat',
    city: 'Surat',
    area: '',
    pincode: '',
    workersNeeded: 10,
    hiringType: 'full_time',
    businessDescription: '',
    gstCertificatePath: '',
    companyProofPath: '',
    ownerIdProofPath: '',
    categoryIds: ['cat-stitching'],
    status: 'active',
    registrationFeePaid: true,
    activePlan: 'company-plan',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  })
  snapshot.jobPosts.push(
    {
      id: 'job-1',
      companyId: 'company-1',
      planId: 'company-plan',
      categoryId: 'cat-stitching',
      title: 'Stitching Operator',
      description: '',
      city: 'Surat',
      locationLabel: 'Surat',
      latitude: null,
      longitude: null,
      workersNeeded: 5,
      wageAmount: 500,
      status: 'live',
      publishedAt: '2026-08-24T00:00:00.000Z',
      expiresAt: '2026-09-10T00:00:00.000Z',
      validityDays: 15,
      createdAt: '2026-08-24T00:00:00.000Z',
      updatedAt: '2026-08-24T00:00:00.000Z',
    },
    {
      id: 'job-2',
      companyId: 'company-1',
      planId: 'company-plan',
      categoryId: 'cat-stitching',
      title: 'Embroidery Operator',
      description: '',
      city: 'Surat',
      locationLabel: 'Surat',
      latitude: null,
      longitude: null,
      workersNeeded: 4,
      wageAmount: 550,
      status: 'live',
      publishedAt: '2026-08-24T00:00:00.000Z',
      expiresAt: '2026-09-10T00:00:00.000Z',
      validityDays: 15,
      createdAt: '2026-08-24T00:00:00.000Z',
      updatedAt: '2026-08-24T00:00:00.000Z',
    },
  )
  snapshot.workers.push(
    {
      id: 'worker-1',
      fullName: 'A',
      mobile: '9876543210',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 600,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'active',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: true,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },
    {
      id: 'worker-2',
      fullName: 'B',
      mobile: '9876543211',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 3,
      expectedDailyWage: 600,
      minimumExpectedWage: 550,
      maximumExpectedWage: 700,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'active',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: true,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },
    {
      id: 'worker-3',
      fullName: 'C',
      mobile: '9876543212',
      city: 'Ahmedabad',
      homeCity: 'Ahmedabad',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 1,
      expectedDailyWage: 450,
      minimumExpectedWage: 400,
      maximumExpectedWage: 500,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'active',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: true,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },
  )

  const plans = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'preview',
    pauseAllSending: true,
    companyConsentStates: {
      'company-1': { matching_alerts_allowed: true },
    },
  })

  assert.equal(plans.length, 1)
  assert.equal(plans[0]?.automationEventType, 'company_matching_digest')
  assert.equal(plans[0]?.matchingWorkerCount, 2)
  assert.equal(plans[0]?.matchingJobCount, 2)
  assert.equal(plans[0]?.liveJobCount, 2)
  assert.equal(plans[0]?.dispatchState, 'blocked')
  assert.equal(plans[0]?.dispatchReason, 'whatsapp-disabled-outside-production')
  assert.equal(plans[0]?.ctaUrl, COMPANY_MATCHING_DIGEST_CTA_URL)
  assert.ok(plans[0]?.maskedMobile.includes('******'))
  assert.deepEqual(
    plans[0]?.metadata.matchedWorkerIds,
    ['worker-1', 'worker-2'],
  )
})

test('worker digest consolidates multiple live matches and requires an injected app link', () => {
  const snapshot = makeSnapshot()
  snapshot.workers.push({
    id: 'worker-1',
    fullName: 'Worker',
    mobile: '9876543210',
    city: 'Surat',
    homeCity: 'Surat',
    salaryType: 'daily',
    companyId: '',
    industryCategory: 'Textile',
    businessType: '',
    address: '',
    preferredWorkLocations: [
      {
        stateOptionId: 'gujarat',
        stateLabel: 'Gujarat',
        cityOptionIds: ['surat'],
        cityLabels: ['Surat'],
      },
    ],
    profilePhotoPath: '',
    resumeDocumentPath: '',
    skills: [],
    experienceYears: 2,
    expectedDailyWage: 500,
    minimumExpectedWage: 450,
    maximumExpectedWage: 550,
    walletBalance: 0,
    registrationFeePaid: true,
    activePlan: 'worker-plan',
    planValidFrom: '2026-08-01',
    planValidUntil: '2099-01-01',
    lastWalletDeductionDate: '',
    workerPausedByWorker: false,
    workerPausedAt: '',
    workerReactivatedAt: '',
    status: 'active',
    kycStatus: 'approved',
    kycRemarks: '',
    availability: 'available_today',
    isVisible: true,
    categoryIds: ['cat-stitching'],
    identityProofType: '',
    identityProofNumber: '',
    identityProofPath: '',
    registrationCompletedAt: '2026-08-01T00:00:00.000Z',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  })
  snapshot.workers.push({
    id: 'worker-expired',
    fullName: 'Expired Worker',
    mobile: '9876543219',
    city: 'Surat',
    homeCity: 'Surat',
    salaryType: 'daily',
    companyId: '',
    industryCategory: 'Textile',
    businessType: '',
    address: '',
    preferredWorkLocations: [],
    profilePhotoPath: '',
    resumeDocumentPath: '',
    skills: [],
    experienceYears: 2,
    expectedDailyWage: 500,
    minimumExpectedWage: 450,
    maximumExpectedWage: 550,
    walletBalance: 0,
    registrationFeePaid: true,
    activePlan: 'worker-plan',
    planValidFrom: '2026-08-01',
    planValidUntil: '2026-08-20',
    lastWalletDeductionDate: '',
    workerPausedByWorker: false,
    workerPausedAt: '',
    workerReactivatedAt: '',
    status: 'active',
    kycStatus: 'approved',
    kycRemarks: '',
    availability: 'available_today',
    isVisible: true,
    categoryIds: ['cat-stitching'],
    identityProofType: '',
    identityProofNumber: '',
    identityProofPath: '',
    registrationCompletedAt: '2026-08-01T00:00:00.000Z',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  })
  snapshot.companies.push(
    {
      id: 'company-1',
      companyName: 'Company 1',
      contactPerson: 'Owner 1',
      email: 'owner1@example.com',
      mobile: '9876500000',
      contactMobile: '9876500000',
      businessType: 'Factory',
      industryCategory: 'Textile',
      gstNumber: '',
      companyAddress: '',
      state: 'Gujarat',
      city: 'Surat',
      area: '',
      pincode: '',
      workersNeeded: 5,
      hiringType: 'full_time',
      businessDescription: '',
      gstCertificatePath: '',
      companyProofPath: '',
      ownerIdProofPath: '',
      categoryIds: ['cat-stitching'],
      status: 'active',
      registrationFeePaid: true,
      activePlan: 'company-plan',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },
    {
      id: 'company-2',
      companyName: 'Company 2',
      contactPerson: 'Owner 2',
      email: 'owner2@example.com',
      mobile: '9876500001',
      contactMobile: '9876500001',
      businessType: 'Factory',
      industryCategory: 'Textile',
      gstNumber: '',
      companyAddress: '',
      state: 'Gujarat',
      city: 'Surat',
      area: '',
      pincode: '',
      workersNeeded: 5,
      hiringType: 'full_time',
      businessDescription: '',
      gstCertificatePath: '',
      companyProofPath: '',
      ownerIdProofPath: '',
      categoryIds: ['cat-stitching'],
      status: 'active',
      registrationFeePaid: true,
      activePlan: 'company-plan',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },
  )
  snapshot.jobPosts.push(
    {
      id: 'job-1',
      companyId: 'company-1',
      planId: 'company-plan',
      categoryId: 'cat-stitching',
      title: 'Job 1',
      description: '',
      city: 'Surat',
      locationLabel: 'Surat',
      latitude: null,
      longitude: null,
      workersNeeded: 2,
      wageAmount: 500,
      status: 'live',
      publishedAt: '2026-08-24T00:00:00.000Z',
      expiresAt: '2026-09-10T00:00:00.000Z',
      validityDays: 15,
      createdAt: '2026-08-24T00:00:00.000Z',
      updatedAt: '2026-08-24T00:00:00.000Z',
    },
    {
      id: 'job-2',
      companyId: 'company-2',
      planId: 'company-plan',
      categoryId: 'cat-stitching',
      title: 'Job 2',
      description: '',
      city: 'Surat',
      locationLabel: 'Surat',
      latitude: null,
      longitude: null,
      workersNeeded: 2,
      wageAmount: 500,
      status: 'live',
      publishedAt: '2026-08-24T00:00:00.000Z',
      expiresAt: '2026-09-10T00:00:00.000Z',
      validityDays: 15,
      createdAt: '2026-08-24T00:00:00.000Z',
      updatedAt: '2026-08-24T00:00:00.000Z',
    },
    {
      id: 'job-city-mismatch',
      companyId: 'company-2',
      planId: 'company-plan',
      categoryId: 'cat-stitching',
      title: 'Job 3',
      description: '',
      city: 'Ahmedabad',
      locationLabel: 'Ahmedabad',
      latitude: null,
      longitude: null,
      workersNeeded: 2,
      wageAmount: 500,
      status: 'live',
      publishedAt: '2026-08-24T00:00:00.000Z',
      expiresAt: '2026-09-10T00:00:00.000Z',
      validityDays: 15,
      createdAt: '2026-08-24T00:00:00.000Z',
      updatedAt: '2026-08-24T00:00:00.000Z',
    },
  )

  const blockedPlans = planWorkerMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    workerConsentStates: {
      'worker-1': { matching_alerts_allowed: true },
    },
  })
  const runnablePlans = planWorkerMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    workerConsentStates: {
      'worker-1': { matching_alerts_allowed: true },
    },
    resolveWorkerAppLink: () => '/app/referral?ref=synthetic',
  })

  assert.equal(blockedPlans.length, 1)
  assert.equal(blockedPlans[0]?.dispatchReason, 'missing_cta_url')
  assert.equal(blockedPlans[0]?.matchingCompanyCount, 2)
  assert.equal(blockedPlans[0]?.matchingJobCount, 2)
  assert.equal(blockedPlans[0]?.ctaUrl, null)
  assert.equal(runnablePlans.length, 1)
  assert.equal(runnablePlans[0]?.dispatchState, 'ready')
  assert.equal(runnablePlans[0]?.matchingCompanyCount, 2)
  assert.equal(runnablePlans[0]?.matchingJobCount, 2)
  assert.equal(runnablePlans[0]?.ctaUrl, '/app/referral?ref=synthetic')
})

test('worker payment or plan reminder planner uses controlled subreasons, excludes paused workers, and stays blocked in preview', () => {
  const snapshot = makeSnapshot()
  snapshot.workers.push(
    {
      id: 'worker-wallet',
      fullName: 'Wallet Worker',
      mobile: '9876543210',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 550,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'inactive_wallet_empty',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: false,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-25T00:00:00.000Z',
    },
    {
      id: 'worker-expired',
      fullName: 'Expired Worker',
      mobile: '9876543211',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 550,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2026-08-20',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'inactive_subscription_expired',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: false,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-25T00:00:00.000Z',
    },
    {
      id: 'worker-paused',
      fullName: 'Paused Worker',
      mobile: '9876543212',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 550,
      walletBalance: 100,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: true,
      workerPausedAt: '2026-08-24T00:00:00.000Z',
      workerReactivatedAt: '',
      status: 'inactive_paused_by_worker',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: false,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-25T00:00:00.000Z',
    },
  )

  const plans = planWorkerPaymentOrPlanReminders({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'preview',
    pauseAllSending: true,
    workerConsentStates: {
      'worker-wallet': { service_allowed: true },
      'worker-expired': { service_allowed: true },
      'worker-paused': { service_allowed: true },
    },
  })

  assert.equal(plans.length, 2)
  assert.deepEqual(
    plans.map((plan) => [plan.recipientId, plan.subreason]),
    [
      ['worker-wallet', 'wallet_empty'],
      ['worker-expired', 'subscription_expired'],
    ],
  )
  assert.equal(plans[0]?.dispatchReason, 'missing_cta_url')
  assert.equal(plans[0]?.messagePreview?.includes('wallet or plan'), true)
  assert.equal(plans[1]?.messagePreview?.includes('plan has expired'), true)
  assert.equal(
    plans[0]?.idempotencyKey,
    buildWhatsappAutomationIdempotencyKey({
      automationEventType: 'worker_payment_or_plan_reminder',
      recipientType: 'worker',
      recipientId: 'worker-wallet',
      variantKey: 'wallet_empty',
      cycleStartsAt: plans[0]?.cycleStartsAt || '',
    }),
  )
})

test('worker service planners require service consent, respect suppression, and keep generic KYC copy free of admin text', () => {
  const snapshot = makeSnapshot()
  snapshot.workers.push(
    {
      id: 'worker-wallet',
      fullName: 'Wallet Worker',
      mobile: '9876543210',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 550,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'inactive_wallet_empty',
      kycStatus: 'approved',
      kycRemarks: '',
      availability: 'available_today',
      isVisible: false,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-25T00:00:00.000Z',
    },
    {
      id: 'worker-rejected',
      fullName: 'Rejected Worker',
      mobile: '9876543211',
      city: 'Surat',
      homeCity: 'Surat',
      salaryType: 'daily',
      companyId: '',
      industryCategory: 'Textile',
      businessType: '',
      address: '',
      preferredWorkLocations: [],
      profilePhotoPath: '',
      resumeDocumentPath: '',
      skills: [],
      experienceYears: 2,
      expectedDailyWage: 500,
      minimumExpectedWage: 450,
      maximumExpectedWage: 550,
      walletBalance: 0,
      registrationFeePaid: true,
      activePlan: 'worker-plan',
      planValidFrom: '2026-08-01',
      planValidUntil: '2099-01-01',
      lastWalletDeductionDate: '',
      workerPausedByWorker: false,
      workerPausedAt: '',
      workerReactivatedAt: '',
      status: 'rejected',
      kycStatus: 'rejected',
      kycRemarks: 'Aadhaar photo mismatch - internal note',
      availability: 'available_today',
      isVisible: false,
      categoryIds: ['cat-stitching'],
      identityProofType: '',
      identityProofNumber: '',
      identityProofPath: '',
      registrationCompletedAt: '2026-08-01T00:00:00.000Z',
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-25T08:30:00.000Z',
    },
  )

  const blockedPaymentPlan = planWorkerPaymentOrPlanReminders({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    suppressedMobiles: ['9876543210'],
  })[0]
  const kycPlans = planWorkerKycRejectedNotifications({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    workerConsentStates: {
      'worker-rejected': { service_allowed: true },
    },
  })

  assert.equal(blockedPaymentPlan?.dispatchReason, 'missing_consent_service_allowed')
  assert.equal(blockedPaymentPlan?.eligibility.reasonCodes.includes('suppressed'), true)
  assert.equal(kycPlans.length, 1)
  assert.equal(kycPlans[0]?.subreason, 'kyc_rejected')
  assert.equal(kycPlans[0]?.dispatchReason, 'missing_cta_url')
  assert.equal(kycPlans[0]?.messagePreview?.includes('Aadhaar'), false)
  assert.equal(kycPlans[0]?.messagePreview?.includes('internal note'), false)
  assert.equal(kycPlans[0]?.metadata.rejectionStateMarkerPresent, true)
  assert.equal(
    kycPlans[0]?.idempotencyKey,
    buildWhatsappAutomationIdempotencyKey({
      automationEventType: 'worker_kyc_rejected',
      recipientType: 'worker',
      recipientId: 'worker-rejected',
      variantKey: 'rejection-state-2026-08-25T08:30:00.000Z',
      cycleStartsAt: kycPlans[0]?.cycleStartsAt || '',
    }),
  )
})

test('quiet hours, suppression, consent, preview blocking, pause gate, and masked idempotency stay fail-closed', () => {
  const snapshot = makeSnapshot()
  snapshot.companies.push({
    id: 'company-1',
    companyName: 'Company',
    contactPerson: 'Owner',
    email: 'owner@example.com',
    mobile: '9876500000',
    contactMobile: '9876500000',
    businessType: 'Factory',
    industryCategory: 'Textile',
    gstNumber: '',
    companyAddress: '',
    state: 'Gujarat',
    city: 'Surat',
    area: '',
    pincode: '',
    workersNeeded: 5,
    hiringType: 'full_time',
    businessDescription: '',
    gstCertificatePath: '',
    companyProofPath: '',
    ownerIdProofPath: '',
    categoryIds: ['cat-stitching'],
    status: 'active',
    registrationFeePaid: true,
    activePlan: 'company-plan',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  })
  snapshot.jobPosts.push({
    id: 'job-1',
    companyId: 'company-1',
    planId: 'company-plan',
    categoryId: 'cat-stitching',
    title: 'Job 1',
    description: '',
    city: 'Surat',
    locationLabel: 'Surat',
    latitude: null,
    longitude: null,
    workersNeeded: 2,
    wageAmount: 500,
    status: 'live',
    publishedAt: '2026-08-24T00:00:00.000Z',
    expiresAt: '2026-09-10T00:00:00.000Z',
    validityDays: 15,
    createdAt: '2026-08-24T00:00:00.000Z',
    updatedAt: '2026-08-24T00:00:00.000Z',
  })
  snapshot.workers.push({
    id: 'worker-1',
    fullName: 'Worker',
    mobile: '9876543210',
    city: 'Surat',
    homeCity: 'Surat',
    salaryType: 'daily',
    companyId: '',
    industryCategory: 'Textile',
    businessType: '',
    address: '',
    preferredWorkLocations: [],
    profilePhotoPath: '',
    resumeDocumentPath: '',
    skills: [],
    experienceYears: 2,
    expectedDailyWage: 500,
    minimumExpectedWage: 450,
    maximumExpectedWage: 550,
    walletBalance: 0,
    registrationFeePaid: true,
    activePlan: 'worker-plan',
    planValidFrom: '2026-08-01',
    planValidUntil: '2099-01-01',
    lastWalletDeductionDate: '',
    workerPausedByWorker: false,
    workerPausedAt: '',
    workerReactivatedAt: '',
    status: 'active',
    kycStatus: 'approved',
    kycRemarks: '',
    availability: 'available_today',
    isVisible: true,
    categoryIds: ['cat-stitching'],
    identityProofType: '',
    identityProofNumber: '',
    identityProofPath: '',
    registrationCompletedAt: '2026-08-01T00:00:00.000Z',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  })

  const previewPlan = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'preview',
    pauseAllSending: false,
    companyConsentStates: {
      'company-1': { matching_alerts_allowed: true },
    },
  })[0]
  const pausedPlan = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: true,
    dryRun: false,
    companyConsentStates: {
      'company-1': { matching_alerts_allowed: true },
    },
  })[0]
  const quietHoursPlan = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T17:30:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    companyConsentStates: {
      'company-1': { matching_alerts_allowed: true },
    },
  })[0]
  const missingConsentPlans = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
  })
  const suppressedPlans = planCompanyMatchingDigests({
    snapshot,
    now: new Date('2026-08-25T06:00:00.000Z'),
    vercelEnv: 'production',
    pauseAllSending: false,
    dryRun: false,
    companyConsentStates: {
      'company-1': { matching_alerts_allowed: true },
    },
    suppressedMobiles: ['9876500000'],
  })

  assert.equal(previewPlan?.dispatchReason, 'whatsapp-disabled-outside-production')
  assert.equal(pausedPlan?.dispatchReason, 'whatsapp-paused')
  assert.equal(quietHoursPlan?.dispatchState, 'queued')
  assert.equal(quietHoursPlan?.dispatchReason, 'inside_quiet_hours')
  assert.equal(
    missingConsentPlans[0]?.dispatchReason,
    'missing_consent_matching_alerts_allowed',
  )
  assert.equal(suppressedPlans[0]?.dispatchReason, 'suppressed')
  assert.equal(previewPlan?.maskedMobile, '+91******0000')
  assert.equal(
    previewPlan?.idempotencyKey,
    buildWhatsappAutomationIdempotencyKey({
      automationEventType: 'company_matching_digest',
      recipientType: 'company',
      recipientId: 'company-1',
      cycleStartsAt: previewPlan?.cycleStartsAt || '',
    }),
  )
})
