import type { AgentLocale } from './agent-types'

export const agentCopy = {
  en: {
    appName: 'Rozgar Agent',
    home: 'Home',
    refer: 'Refer',
    referrals: 'Referrals',
    earnings: 'Earnings',
    profile: 'Profile',
    categories: 'Categories',
    installAgentApp: 'Install Agent App',
    installHint: 'Add Rozgar Agent to your home screen for a faster app-like experience.',
    installFallback: 'Use your browser menu and choose Add to Home Screen if the install prompt is unavailable.',
    welcomeBack: 'Welcome back',
    availableEarnings: 'Available Earnings',
    totalReferred: 'Total Referred',
    registered: 'Registered',
    kycPending: 'KYC Pending',
    qualified: 'Qualified',
    rejected: 'Rejected',
    shareReferralLink: 'Share Referral Link',
    viewReferrals: 'View Referrals',
    viewEarnings: 'View Earnings',
    referralCode: 'Referral Code',
    referralLink: 'Referral Link',
    copyCode: 'Copy Code',
    copyLink: 'Copy Link',
    share: 'Share',
    whatsappShare: 'WhatsApp Share',
    codeCopied: 'Referral code copied.',
    linkCopied: 'Referral link copied.',
    eligibleCategories: 'Eligible Categories',
    earnPrefix: 'Earn',
    referralEarningsSeparate: 'Referral earnings are separate from your Rozgar worker wallet.',
    workerWallet: 'Rozgar Worker Wallet',
    lifetimeEarned: 'Lifetime Earned',
    yourReferralCode: 'Your Referral Code',
    yourReferralLink: 'Your Referral Link',
    shareOnWhatsapp: 'Share on WhatsApp',
    moreShareOptions: 'More Share Options',
    howItWorks: 'How it Works',
    viewDetails: 'View Details',
    referHeroTitleLine1: 'Refer Workers,',
    referHeroTitleLine2: 'Earn Rewards',
    referHeroSubtitle: 'Invite more workers to Rozgar and earn attractive rewards.',
    referHeroTrusted: 'Trusted by 1000+ Agents',
    stepShareLink: 'Share Link\nwith Workers',
    stepWorkerRegisters: 'Worker\nRegisters',
    stepCompletesVerification: 'Completes\nVerification',
    stepYouEarnReward: 'You Earn\nReward',
    eligibleCategoriesHint: 'Share eligible categories and earn rewards when workers register & get approved.',
    perQualifiedWorker: 'Per Qualified Worker',
    shareNow: 'Share Now',
    notificationsComingSoon: 'Notifications coming soon.',
    withdrawalComingSoonTitle: 'Withdrawal Coming Soon',
    withdrawalComingSoonBody: 'Your referral earnings are safe. Withdrawal facility will be available soon.',
    ok: 'OK',
    showLess: 'Show Less',
    pending: 'Pending',
    available: 'Available',
    withdrawn: 'Withdrawn',
    noReferralHistory: 'No referral history yet.',
    noCategories: 'No eligible categories are assigned yet.',
    all: 'All',
    referralDate: 'Referral Date',
    rewardAmount: 'Reward Amount',
    rewardStatus: 'Reward Status',
    category: 'Category',
    worker: 'Worker',
    mobile: 'Mobile',
    kycStatus: 'KYC Status',
    status: 'Status',
    support: 'Support',
    logout: 'Logout',
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    activeAgent: 'Active Agent',
    returnToRozgar: 'Return to Rozgar',
    disabledTitle: 'Refer & Earn is not enabled for your account yet.',
    disabledBody: 'Your mobile number is verified, but Agent access is not active for this account.',
    loginTitle: 'Agent Login',
    loginSubtitle: 'Use your mobile number and OTP to open your Rozgar Agent dashboard.',
    mobilePlaceholder: 'Enter mobile number',
    otpPlaceholder: 'Enter OTP',
    requestOtp: 'Request OTP',
    verifyOtp: 'Verify OTP',
    resendOtp: 'Resend OTP',
    changeMobileNumber: 'Change mobile number',
    otpRequested: 'OTP sent. Enter the code received on your phone.',
    otpInfo: 'User enters OTP directly on the phone. No OTP is exposed in chat.',
    verifying: 'Verifying...',
    requesting: 'Sending OTP...',
    openAgentDashboard: 'Open dashboard',
    agentStatus: 'Agent Status',
    quickActions: 'Quick Actions',
    installNow: 'Install Now',
    referralsOnly: 'Only your own referrals are visible here.',
    historyNote: 'Private worker details stay hidden. Reward history is read-only.',
    logoutDone: 'Logged out successfully.',
    pageError: 'Unable to load this Agent page right now.',
  },
  hi: {
    appName: 'रोजगार एजेंट',
    home: 'होम',
    refer: 'रेफर करें',
    referrals: 'रेफरल',
    earnings: 'कमाई',
    profile: 'प्रोफाइल',
    categories: 'श्रेणियां',
    installAgentApp: 'एजेंट ऐप इंस्टॉल करें',
    installHint: 'तेज़, ऐप-जैसे अनुभव के लिए Rozgar Agent को होम स्क्रीन पर जोड़ें।',
    installFallback: 'यदि इंस्टॉल प्रॉम्प्ट न दिखे तो ब्राउज़र मेनू से Add to Home Screen चुनें।',
    welcomeBack: 'फिर से स्वागत है',
    availableEarnings: 'उपलब्ध कमाई',
    totalReferred: 'कुल रेफरल',
    registered: 'रजिस्टर्ड',
    kycPending: 'KYC लंबित',
    qualified: 'योग्य',
    rejected: 'अस्वीकृत',
    shareReferralLink: 'रेफरल लिंक शेयर करें',
    viewReferrals: 'रेफरल देखें',
    viewEarnings: 'कमाई देखें',
    referralCode: 'रेफरल कोड',
    referralLink: 'रेफरल लिंक',
    copyCode: 'कोड कॉपी करें',
    copyLink: 'लिंक कॉपी करें',
    share: 'शेयर',
    whatsappShare: 'व्हाट्सऐप शेयर',
    codeCopied: 'रेफरल कोड कॉपी हो गया।',
    linkCopied: 'रेफरल लिंक कॉपी हो गया।',
    eligibleCategories: 'योग्य श्रेणियां',
    earnPrefix: 'कमाएं',
    referralEarningsSeparate: 'रेफरल कमाई आपकी Rozgar worker wallet से अलग है।',
    workerWallet: 'Rozgar Worker Wallet',
    lifetimeEarned: 'कुल कमाई',
    yourReferralCode: 'आपका रेफरल कोड',
    yourReferralLink: 'आपका रेफरल लिंक',
    shareOnWhatsapp: 'व्हाट्सऐप पर साझा करें',
    moreShareOptions: 'अन्य साझा विकल्प',
    howItWorks: 'यह कैसे काम करता है',
    viewDetails: 'विवरण देखें',
    referHeroTitleLine1: 'कामगार रेफर करें,',
    referHeroTitleLine2: 'इनाम कमाएं',
    referHeroSubtitle: 'अधिक कामगारों को रोज़गार से जोड़ें और आकर्षक इनाम कमाएं।',
    referHeroTrusted: '1000+ एजेंट्स का भरोसा',
    stepShareLink: 'कामगारों के साथ\nलिंक साझा करें',
    stepWorkerRegisters: 'कामगार\nपंजीकरण करता है',
    stepCompletesVerification: 'सत्यापन\nपूरा करता है',
    stepYouEarnReward: 'आपको इनाम\nमिलता है',
    eligibleCategoriesHint: 'योग्य श्रेणियां साझा करें और कामगारों के पंजीकरण व स्वीकृति के बाद इनाम कमाएं।',
    perQualifiedWorker: 'प्रति योग्य कामगार',
    shareNow: 'अभी साझा करें',
    notificationsComingSoon: 'नोटिफिकेशन जल्द आएंगे।',
    withdrawalComingSoonTitle: 'निकासी सुविधा जल्द उपलब्ध होगी',
    withdrawalComingSoonBody: 'आपकी रेफरल कमाई सुरक्षित है। निकासी की सुविधा जल्द उपलब्ध होगी।',
    ok: 'ठीक है',
    showLess: 'कम दिखाएँ',
    pending: 'लंबित',
    available: 'उपलब्ध',
    withdrawn: 'निकाला गया',
    noReferralHistory: 'अभी कोई रेफरल हिस्ट्री नहीं है।',
    noCategories: 'अभी कोई योग्य श्रेणी असाइन नहीं की गई है।',
    all: 'सभी',
    referralDate: 'रेफरल तारीख',
    rewardAmount: 'रिवार्ड राशि',
    rewardStatus: 'रिवार्ड स्थिति',
    category: 'श्रेणी',
    worker: 'वर्कर',
    mobile: 'मोबाइल',
    kycStatus: 'KYC स्थिति',
    status: 'स्थिति',
    support: 'सहायता',
    logout: 'लॉगआउट',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी',
    activeAgent: 'सक्रिय एजेंट',
    returnToRozgar: 'रोजगार पर वापस जाएं',
    disabledTitle: 'रेफर एंड अर्न अभी आपके खाते के लिए सक्षम नहीं है।',
    disabledBody: 'आपका मोबाइल सत्यापित है, लेकिन इस खाते के लिए एजेंट एक्सेस सक्रिय नहीं है।',
    loginTitle: 'एजेंट लॉगिन',
    loginSubtitle: 'Rozgar Agent dashboard खोलने के लिए मोबाइल नंबर और OTP का उपयोग करें।',
    mobilePlaceholder: 'मोबाइल नंबर दर्ज करें',
    otpPlaceholder: 'OTP दर्ज करें',
    requestOtp: 'OTP भेजें',
    verifyOtp: 'OTP सत्यापित करें',
    resendOtp: 'OTP फिर भेजें',
    changeMobileNumber: 'मोबाइल नंबर बदलें',
    otpRequested: 'OTP भेज दिया गया है। अपने फोन पर मिला कोड दर्ज करें।',
    otpInfo: 'OTP केवल फोन पर डाला जाएगा। चैट में OTP नहीं दिखाया जाता।',
    verifying: 'सत्यापित हो रहा है...',
    requesting: 'OTP भेजा जा रहा है...',
    openAgentDashboard: 'डैशबोर्ड खोलें',
    agentStatus: 'एजेंट स्थिति',
    quickActions: 'त्वरित कार्य',
    installNow: 'अभी इंस्टॉल करें',
    referralsOnly: 'यहां केवल आपके अपने रेफरल दिखते हैं।',
    historyNote: 'वर्कर की निजी जानकारी छिपी रहती है। रिवार्ड हिस्ट्री केवल पढ़ने योग्य है।',
    logoutDone: 'सफलतापूर्वक लॉगआउट हो गया।',
    pageError: 'यह Agent पेज अभी लोड नहीं हो सका।',
  },
} as const satisfies Record<AgentLocale, Record<string, string>>

export type AgentCopy = (typeof agentCopy)[AgentLocale]
